### ISSUE TITLE
Bot randomly crashing and rebooting

### ISSUE THREAD

**Issue by Stefouch** [Stefouch/sebedius-yearzero-discord-bot#133]
Some users reported me that the bot was sometimes unresponsive.

Upon investigation of the logs, I observed that the bot is rebooting very frequently since around March 15th, 2022.

Here is the error I found that was crashing the bot. It can appears with any command and at random times:

```js
/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11
      const existing = channel.messages.cache.get(data.id);
                                        ^
TypeError: Cannot read property 'cache' of undefined
    at MessageCreateAction.handle (/app/node_modules/discord.js/src/client/actions/MessageCreate.js:11:41)
    at Object.module.exports [as MESSAGE_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:301:10)
    at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:873:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:517:14)
```

It looks like an issue related with the messages cache. Either due to a change in the Discord API, an insufficient cache size, or something else.

**Comment by Stefouch** [comment]
**Related:**
https://stackoverflow.com/questions/72077172/typeerror-cannot-read-properties-of-undefined-reading-cache-discord-js

**Solution:**
Update DiscordJS to 13
