### ISSUE TITLE
Botinfo error

### ISSUE THREAD

**Issue by Stefouch** [Stefouch/sebedius-yearzero-discord-bot#77]
Heroku Log:
```
2020-12-10T10:21:51.807879+00:00 app[worker.1]: Botinfo Error TypeError: Cannot read property 'cache' of undefined
2020-12-10T10:21:51.807897+00:00 app[worker.1]:     at botInfo (/app/commands/admin.js:204:34)
2020-12-10T10:21:51.807898+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-12-10T10:21:51.807898+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-10T10:21:51.807899+00:00 app[worker.1]:     at async Object.run (/app/commands/admin.js:41:41)
2020-12-10T10:21:51.807899+00:00 app[worker.1]:     at async Sebedius.<anonymous> (/app/bot.js:143:3)
```

**Comment by Stefouch** [comment]
```js
.addField('Users', ctx.guilds.cache.reduce((sum, g) => sum + g.memberCount), true)
↓
.addField('Users', ctx.bot.guilds.cache.reduce((sum, g) => sum + g.memberCount), true)
```

**Comment by Stefouch** [comment]
Still buggy:
```
2020-12-15T07:12:10.012763+00:00 app[worker.1]: Botinfo Error DiscordAPIError: Invalid Form Body
2020-12-15T07:12:10.012773+00:00 app[worker.1]: embed.fields[3].value: Must be 1024 or fewer in length.
2020-12-15T07:12:10.012774+00:00 app[worker.1]:     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
2020-12-15T07:12:10.012775+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2020-12-15T07:12:10.012775+00:00 app[worker.1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-15T07:12:10.012776+00:00 app[worker.1]:     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
2020-12-15T07:12:10.012777+00:00 app[worker.1]:     at async ContextMessage.send (/app/utils/ContextMessage.js:43:15)
2020-12-15T07:12:10.012777+00:00 app[worker.1]:     at async botInfo (/app/commands/admin.js:215:3)
2020-12-15T07:12:10.012777+00:00 app[worker.1]:     at async Object.run (/app/commands/admin.js:41:41)
2020-12-15T07:12:10.012778+00:00 app[worker.1]:     at async Sebedius.<anonymous> (/app/bot.js:143:3) {
2020-12-15T07:12:10.012778+00:00 app[worker.1]:   method: 'post',
2020-12-15T07:12:10.012779+00:00 app[worker.1]:   path: '/channels/585853622345138289/messages',
2020-12-15T07:12:10.012780+00:00 app[worker.1]:   code: 50035,
2020-12-15T07:12:10.012780+00:00 app[worker.1]:   httpStatus: 400
2020-12-15T07:12:10.012781+00:00 app[worker.1]: }
```
